"""
Django settings for prjtBDDGL project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

from dotenv import load_dotenv
load_dotenv()

ASGI_APPLICATION = 'BackendProjetGLBDD.asgi.application'


#DEVELOPMENT = 'live'
# DEVELOPMENT = "local"
# DEBUG = True


# if DEVELOPMENT == "local":
#     # Development
#     DEBUG = True
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": "sara",  # The name of your local database
#             "USER": "devnoms_localdb",  # Your PostgreSQL username
#             "PASSWORD": "sarasara",  # Your PostgreSQL password
#             "HOST": "localhost",  # Use "localhost" if PostgreSQL is on your local machine
#             "PORT": "5432",  # Default PostgreSQL port
#         }
#     }
#     SITE_URL = "http://localhost:8000"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^iwo01s_=zt2$0f5u@#p$!xqh*cs1e+8v*l595=mmgfqn!s_(^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1','dzartisan-app.onrender.com']


# Application definition

INSTALLED_APPS = [
    "channels",
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'app',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'userauths',
    "chat",
    "corsheaders",
]

CHANNEL_LAYERS = {
     "default": {
         "BACKEND": "channels.layers.InMemoryChannelLayer",
     }
 }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    "corsheaders.middleware.CorsMiddleware",
]

SOCIALACCOUNT_LOGIN_ON_GET=True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        "SCOPE":[
            "profile",
            "email",
        ],
        'APP': {
            'client_id': '91173687526-q42bulbpo3uu11mj17kmrs4vmqgl586m.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

ROOT_URLCONF = 'BackendProjetGLBDD.urls'


WSGI_APPLICATION = 'BackendProjetGLBDD.wsgi.application'


DATABASES = {
    'default': dj_database_url.parse(os.getenv('DATABASE_URL'), conn_max_age=600, ssl_require=True)

}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CKEDITOR_UPLOAD_PATH = 'uploads/'

# LOGIN_URL = "userauths:sign-in"

# LOGIN_REDIRECT_URL = "/"

# LOGOUT_REDIRECT_URL = "/"

# AUTH_USER_MODEL = 'userauths.User's


STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # default
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name


SESSION_COOKIE_AGE = 300  # 2 weeks in seconds (default)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # False by default; session persists after browser close


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory (optional)
        'APP_DIRS': True,  # Looks for templates in each app's templates/ directory
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:5500",
#     "http://localhost:3000",
#     "https://devnoms.onrender.com",
#     "https://django-chat-application.onrender.com",
# ]


# CSRF_TRUSTED_ORIGINS = [
#     "https://devnoms.onrender.com",
#     "https://django-chat-application.onrender.com",
# ]

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, "templates")],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]




# Cookie settings
SESSION_COOKIE_SAMESITE = 'Lax'  # Use 'Lax' or 'Strict' for SameSite
SESSION_COOKIE_SECURE = True  # Set to True in production with HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'  # Use 'Lax' or 'Strict' for SameSite
CSRF_COOKIE_SECURE = True  # Set to True in production with HTTPS

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins (for development only)
CORS_ALLOW_CREDENTIALS = True  # Allow credentials (cookies) to be sent

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # Add your frontend origin(s) here
    "http://127.0.0.1:3000",
    "https://dzartisan-app.onrender.com",  # Add your production frontend URL
    "onecs-project.onrender.com"
]


